#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/.env-newsboat

if [[ -d $directorio_git_newsboat ]]; then
    echo "Directorio existe";
    number=""
    while [[ ! $number =~ ^[1-3]{1} ]]; do
        read -p " [1] Subir a Github`echo $'\n\r'` [2] Descargar de Github:`echo $'\n\r'` [3] Salir: `echo $'\n\r'`> " number
        case $number in
            [1]* ) echo "Subir a Github";
                cp -pvu $directorio_local_newsboat/cache.db $directorio_git_newsboat;
                cp -pvu $directorio_local_newsboat/urls $directorio_git_newsboat;
                git -C "$directorio_git" add -A;
                git -C "$directorio_git" commit -m "Update Newsboat $(date +%m/%d/%Y)";
                git -C "$directorio_git" push;
                exit 0;;
            [2]* ) echo "Descargar de Github:";
                git -C "$directorio_git" pull;
                cp -pvu $directorio_git_newsboat/cache.db $directorio_local_newsboat/;
                cp -pvu $directorio_git_newsboat/urls $directorio_local_newsboat/;
                exit 0;;
            [3]* ) exit 0;;
            * ) echo "Elige 1 o 2";;
        esac
    done
else
    echo "Directorio no existe";
    exit 1
fi
